### ISSUE TITLE
HTML Minification?

### ISSUE THREAD

**Issue by jmuehlner** [keithbranton/angular-maven-plugin#8]
It would be really awesome if this tool supported minifying the templates when they're put into the cache.

**Comment by keithbranton** [comment]
Normally you would want to aggregate and minify all the other javascript in addition to the templates. Other plugins do this really well. I use the net.alchim31.maven:yuicompressor-maven-plugin on my own project and we use the wro4j plugin at work (which would probably be a better destination for my plugin's behavior too)
